# Generated by Django 4.2.9 on 2025-02-07 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
