# Generated by Django 5.1.5 on 2025-02-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_book_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
