# Generated by Django 5.1.5 on 2025-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_book_stock_alter_book_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='caminho/para/imagem/default.jpg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
