# Generated by Django 5.1.5 on 2025-02-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0006_alter_book_description_alter_comment_text_ratinstar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatinStar',
        ),
    ]
