# Generated by Django 5.1.5 on 2025-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0009_ratinstar_n_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='media_rating',
            field=models.IntegerField(default=0),
        ),
    ]
