# Generated by Django 5.1.5 on 2025-02-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0010_book_media_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='media_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
