# Generated by Django 5.1.5 on 2025-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0013_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.IntegerField(default=00000000000),
            preserve_default=False,
        ),
    ]
