# Generated by Django 5.1.5 on 2025-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0015_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.BigIntegerField(default=0),
        ),
    ]
