# Generated by Django 5.1.5 on 2025-02-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0017_remove_userprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
