# Generated by Django 5.1.5 on 2025-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0019_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinstar',
            name='genre',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
