# Generated by Django 5.1.5 on 2025-02-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0022_remove_cartitem_cart_remove_cartitem_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
