# Generated by Django 5.1.5 on 2025-03-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0025_userprofile_city_userprofile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cep',
            field=models.IntegerField(null=True),
        ),
    ]
