# Generated by Django 5.1.7 on 2025-03-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0027_userprofile_friends_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='friends',
            new_name='followers',
        ),
    ]
