# Generated by Django 5.1.7 on 2025-07-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0029_userprofile_following_alter_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
